services:
  - type: web
    name: pi-website-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.17.0

  - type: web
    name: pi-website-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: pi-website-db
          property: connectionString
      - key: NOTION_API_KEY
        sync: false
      - key: NOTION_DATABASE_ID
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

databases:
  - name: pi-website-db
    databaseName: pi_website_db
    user: pi_user
        value: dcbeckyco
      - key: CLOUDINARY_KEY
        value: 993325454266224
      - key: CLOUDINARY_SECRET
        value: QU_9samR93xRoeLIs9JZes_RvLw

databases:
  - name: pi-website-db
    plan: free
    databaseName: pi_website_db
    ipAllowList: [] # Allow all IP addresses to access the database
