services:
  - type: web
    name: pi-website-backend
    env: node
    buildCommand: npm install --legacy-peer-deps && NODE_ENV=production npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: DATABASE_CLIENT
        value: postgres
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: pi-website-db
          property: connectionString
      - key: DATABASE_SSL
        value: true

databases:
  - name: pi-website-db
    plan: free
    databaseName: pi_website_db
    ipAllowList: [] # Allow all IP addresses to access the database
